# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a13ece28d200c1e8cb128078d0891cf822e26d9c7743d5b17369dca2341b6380e9eeb7b414a6e2ee9dd85b39284621cbd0998d6183a9ebbc18a550c1c1db1179

test:
  secret_key_base: 4afc672cb13941bf33e67363cc6b4821ec36658d81c48c400d9562e290ca2f89d32864e4da07e4123f2333652f0dfa5f7d36816d5a71cd2e97ea621ca711835f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
